[theme]
primaryColor = "#4CAF50"  # Button and highlight colors
backgroundColor = "#FFFFFF"  # White overall background
secondaryBackgroundColor = "#A7D7C5"  # Sidebar background color
textColor = "#000000"  # Black text for readability
